# ******** Flow control - 'range' ********

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  myValue: "Hello world"
  {{- with .Values.favorite }}
  drink: {{ .drink | upper | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote}}
    {{- end}}
  config.json: |-
    {
  {{- range $key, $val := .Values.json }}
  {{ $key | quote | indent 6}}: {{ $val | quote }}
  {{- end}}
    }
 



 {{/* {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  release: {{ .Release.Name }}
  {{- end }} */}}


  {{/* {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}
  release: {{ .Release.Name }} */}}